// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAujaK4aRq8zgQ2DWutrOgOy7ttuNso-lc',
    appId: '1:515964117208:web:dae2a3c736f17ba8da37ad',
    messagingSenderId: '515964117208',
    projectId: 'smartpath-app-e986d',
    authDomain: 'smartpath-app-e986d.firebaseapp.com',
    storageBucket: 'smartpath-app-e986d.firebasestorage.app',
    measurementId: 'G-WN3PCDWDEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSgBqZm0DLyYaRjAHmFmGFGC4j2FgPG1Y',
    appId: '1:515964117208:android:d9a3ce41ea2d7eb7da37ad',
    messagingSenderId: '515964117208',
    projectId: 'smartpath-app-e986d',
    storageBucket: 'smartpath-app-e986d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSaLUw1mYbmwxONG4IxheUmoZxWyGmRCs',
    appId: '1:515964117208:ios:c52e9463d68d5b3dda37ad',
    messagingSenderId: '515964117208',
    projectId: 'smartpath-app-e986d',
    storageBucket: 'smartpath-app-e986d.firebasestorage.app',
    iosBundleId: 'com.example.smartpathApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSaLUw1mYbmwxONG4IxheUmoZxWyGmRCs',
    appId: '1:515964117208:ios:c52e9463d68d5b3dda37ad',
    messagingSenderId: '515964117208',
    projectId: 'smartpath-app-e986d',
    storageBucket: 'smartpath-app-e986d.firebasestorage.app',
    iosBundleId: 'com.example.smartpathApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAujaK4aRq8zgQ2DWutrOgOy7ttuNso-lc',
    appId: '1:515964117208:web:60fd6c470bc85ba4da37ad',
    messagingSenderId: '515964117208',
    projectId: 'smartpath-app-e986d',
    authDomain: 'smartpath-app-e986d.firebaseapp.com',
    storageBucket: 'smartpath-app-e986d.firebasestorage.app',
    measurementId: 'G-BKHK6FE810',
  );
}
